### ISSUE TITLE
Old references to instructure-bridge

### ISSUE THREAD

**Issue by viplezer** [CorbanR/nixpkgs#1]
@CorbanR you might want to fix these old references to the old instructure-bridge org:

https://github.com/CorbanR/nixpkgs/blob/62c241112676ac395e62e86adeb2ebdd4840dccc/pkgs/applications/virtualization/truss-cli/default.nix#L8

👋

**Comment by CorbanR** [comment]
Thank you @viplezer ! I have fixed them
