### ISSUE TITLE
Contribute libpuslar to upstream

### ISSUE THREAD

**Issue by blackheaven** [CorbanR/nixpkgs#2]
Hello,

I have found out your libpulsar derivation and, I would like to you use it, would you mind to make a contribution to upstream? (I can do it on your behalf if you're lacking time)

Thanks in advance,
Regards.

**Comment by CorbanR** [comment]
sure, I don't mind.

**Comment by CorbanR** [comment]
already submitted and merged upstream via https://github.com/NixOS/nixpkgs/commit/d59d843f217ccbeea57938be1eca3a15bdd71cb9
